apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mm2-offset-map.fullname" . }}
  labels:
    {{- include "mm2-offset-map.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mm2-offset-map.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mm2-offset-map.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mm2-offset-map.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- if .Values.applicationYamlSecret.name }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:{{ .Values.applicationYamlSecret.mountPath }}"
            {{- else }}
            - name: SPRING_APPLICATION_JSON
              {{- if .Values.configSecret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configSecret.name }}
                  key: {{ .Values.configSecret.key }}
              {{- else }}
              value: {{ .Values.config | toJson | quote }}
              {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.applicationYamlSecret.name .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.applicationYamlSecret.name }}
            - name: application-yaml
              mountPath: {{ .Values.applicationYamlSecret.mountPath }}
              subPath: application.yaml
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.applicationYamlSecret.name .Values.extraVolumes }}
      volumes:
        {{- if .Values.applicationYamlSecret.name }}
        - name: application-yaml
          secret:
            secretName: {{ .Values.applicationYamlSecret.name }}
            items:
              - key: {{ .Values.applicationYamlSecret.key }}
                path: application.yaml
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
